/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

interface ContentWrapperProps {
  children: React.ReactNode;
}

const ContentWrapper: React.FC<ContentWrapperProps> = ({ children }) => {
  return (
    <div className="flex flex-col justify-center items-center py-1 pr-7 pl-8 w-full max-w-full border border-yellow-200 border-solid min-h-[83px] rounded-[32px] max-md:px-5">
      {children}
    </div>
  );
};

export default ContentWrapper;
