/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

interface ImageDisplayProps {
  images: { src: string; alt: string }[];
}

const ImageDisplay: React.FC<ImageDisplayProps> = ({ images }) => {
  return (
    <section className="flex flex-row flex-wrap gap-10 justify-center max-md:max-w-full">
      {images.map((image, index) => (
        <img
          key={index}
          loading="lazy"
          src={image.src}
          alt={image.alt}
          className="object-contain self-stretch my-auto aspect-[3.69] min-w-[240px] w-[255px]"
        />
      ))}
    </section>
  );
};

export default ImageDisplay;
