/**
 * This code was generated by Builder.io.
 */
import React from "react";
import HeroText from "./HeroText";
import AddBotButton from "./AddBotButton";

interface FwenBotHeroProps {
  imageSrc: string;
  imageAlt: string;
}

const FwenBotHero: React.FC<FwenBotHeroProps> = ({ imageSrc, imageAlt }) => {
  return (

  );
};

export default FwenBotHero;
