export const phases = [
    {
        number: 1,
        step: [0, 0.2],
        bg: '#FEF08A',
        items: [
            'Release of MVP to introduce Fwen Bot.',
            'Intuitive trading features which allows users to buy and sell on Discord.',
            'Shilling features which allows users to share great tokens within their communities.',
        ],
    },
    {
        number: 2,
        step: [0.15, 0.35],
        bg: '#E5F4A5',
        items: [
            'Introduction to advanced sniping features that allow users to execute trades with precision timing, targeting the best possible entry points.',
            'Limit Orders & Stop loss functionalities that enables users to set predefined price levels to ensure that they never miss a beat.',
        ],
    },
    {
        number: 3,
        step: [0.3, 0.45],
        bg: '#CFF7D1',
        items: [
            'Introduce tools that allow users to track wallets of their choice on huge movements made by whales. ',
            'AI-driven features that offer predictive analytics and market trend analysis to ensure that our community members are always well-informed every step of the way.',
        ],
    },
    {
        number: 4,
        step: [0.4, 0.6],
        bg: '#A8E3E1',
        items: [
            'Introduce support for multi-chain wallets, enabling users to manage their assets across chains.',
            'Feature whereby users can trade beyond Solana and Pump Fun.',
        ],
    },
    {
        number: 5,
        step: [0.55, 0.75],
        bg: '#BDE0FE',

        items: [
            'By going through tokenization, we aim to empower the community by giving them a voice in the future developments and direction of Fwen Bot.',
            'Tokenization will also provide users with more incentives, such as being eligible for a revenue-sharing model that allows them to earn a portion of the fees generated by Fwen Bot.',
        ],
    },
    {
        number: 6,
        step: [0.7, 0.9],
        bg: '#B2D0FF',
        items: [
            'We are just getting started and Fwen Bot is committed to ongoing developments with more groundbreaking features and enhancements on the horizon.',
            'More updates and announcements are in the pipeline and we are looking to explore new possibilities and push boundaries together with our community.',
        ],
    },
]
