/**
 * This code was generated by Builder.io.
 */
import React from "react";

const AddBotButton: React.FC = () => {
  return (
    <button className="overflow-hidden gap-2.5 self-start px-8 py-4 mt-16 text-2xl font-medium text-center text-black bg-cyan-200 rounded-2xl border border-black border-solid shadow-[4px_4px_0px_rgba(0,0,0,1)] max-md:px-5 max-md:mt-10">
      Add Bot To Server
    </button>
  );
};

export default AddBotButton;
