/**
 * This code was generated by Builder.io.
 */
import React from 'react'

const HeroText: React.FC = () => {
    return (
        <>
            <h1 className="text-4xl font-normal max-md:max-w-full">
                As the saying goes, &quot;A friend in need is a friend
                indeed&quot;.
            </h1>
            <p className="mt-5 text-xl max-md:max-w-full">
                Designed as a Discord Trading Bot, Fwen Bot provides the best
                support you need, whenever you need it.
            </p>
        </>
    )
}

export default HeroText
