/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

interface ContentWrapperProps {
  children: React.ReactNode;
}

const ContentWrapper: React.FC<ContentWrapperProps> = ({ children }) => {
  return (
    <div className="flex flex-col justify-center items-center w-full max-w-full min-h-[83px]">
      {children}
    </div>
  );
};

export default ContentWrapper;
