/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Logo: React.FC = () => {
  return (
    <div className="flex flex-col items-end w-40">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/12dee28c0bfcd8dcfaec399d6f2e0ec3979336308d3a8c08344cb84e4626ebcb?placeholderIfAbsent=true&apiKey=7c31e4cd04e948ec8281a96957eed171"
        alt="Company logo"
        className="object-contain w-40 max-w-full aspect-[1.32]"
      />
    </div>
  );
};

export default Logo;
