/**
 * This code was generated by Builder.io.
 */
import { motion } from 'framer-motion'
import React from 'react'

const sitemapLinks = [
    'Home',
    'About us',
    'Features',
    'Roadmap',
    'Recent Updates',
    'F.A.Q',
]

const SitemapLinks: React.FC = () => {
    return (
        <nav className="flex md:w-[200px] flex-col">
            <h2 className="md:ml-4 text-2xl font-medium opacity-60">Sitemap</h2>
            <ul className="mt-2 flex gap-2 w-[200px] max-w-full flex-col justify-between  text-black">
                {sitemapLinks.map((link, index) => (
                    <motion.li className='cursor-pointer rounded-xl bg-white/0 px-4 py-2'

                        whileHover={{ backgroundColor: 'rgba(255,255,255,0.5)' }}

                        key={index}>{link}</motion.li>
                ))}
            </ul>
        </nav>
    )
}

export default SitemapLinks
