/**
 * This code was generated by Builder.io.
 */
import React from 'react'

const sitemapLinks = [
    'Home',
    'About us',
    'Features',
    'Roadmap',
    'Recent Updates',
    'F.A.Q',
]

const SitemapLinks: React.FC = () => {
    return (
        <nav className="flex md:w-[200px] flex-col">
            <h2 className="text-2xl font-medium opacity-60">Sitemap</h2>
            <ul className="mt-2 flex gap-2 w-[200px] max-w-full flex-col justify-between  text-black">
                {sitemapLinks.map((link, index) => (
                    <li className='cursor-pointer hover:font-semibold' key={index}>{link}</li>
                ))}
            </ul>
        </nav>
    )
}

export default SitemapLinks
