/**
 * This code was generated by Builder.io.
 */
import React from 'react'

const sitemapLinks = [
    'Home',
    'About us',
    'Features',
    'Tokenomics',
    'Roadmap',
    'Recent Updates',
    'F.A.Q',
]

const SitemapLinks: React.FC = () => {
    return (
        <nav className="flex w-[200px] flex-col">
            <h2 className="text-2xl font-medium opacity-60">Sitemap</h2>
            <ul className="flex min-h-[215px] w-[200px] max-w-full flex-col justify-between text-xl text-black">
                {sitemapLinks.map((link, index) => (
                    <li key={index}>{link}</li>
                ))}
            </ul>
        </nav>
    )
}

export default SitemapLinks
