/**
 * This code was generated by Builder.io.
 */
import React from 'react'

const usefulLinks = ['Whitepaper']

const UsefulLinks: React.FC = () => {
    return (
        <nav className="flex w-[200px] flex-col">
            <h2 className="text-2xl font-medium opacity-60">Useful Links</h2>
            <ul className="flex w-full flex-col whitespace-nowrap mt-2 text-black">
                {usefulLinks.map((link, index) => (
                    <li className='cursor-pointer hover:font-semibold' key={index}>{link}</li>
                ))}
            </ul>
        </nav>
    )
}

export default UsefulLinks
