/**
 * This code was generated by Builder.io.
 */
import React from 'react'
import Button from '@/components/Button'
import Logo from './Logo'
import NavigationItem from './NavigationItem'

interface HeaderProps {
    logoSrc: string
    navItems: string[]
}

const Header: React.FC<HeaderProps> = ({ logoSrc, navItems }) => {
    return (
        <header className="flex w-full flex-wrap items-center justify-between gap-10 overflow-hidden border-b border-black px-6 pb-6 pt-3 text-base font-medium max-md:max-w-full max-md:px-5">
            <Logo src={logoSrc} />
            <nav className="my-auto flex min-w-[240px] items-center justify-center gap-5 self-stretch max-md:max-w-full">
                {navItems.map((item, index) => (
                    <NavigationItem key={index} text={item} />
                ))}
                <Button text="Get Started" primary className="!px-4 !py-2" />
            </nav>
        </header>
    )
}

export default Header
