/**
 * This code was generated by Builder.io.
 */
import React from 'react'

interface LogoProps {
    src: string
}

const Logo: React.FC<LogoProps> = ({ src }) => {
    return (
        <div className='flex justify-start'>
            <img
                loading="lazy"
                src={src}
                alt="Company Logo"
                className="my-auto aspect-[4.12] w-28 shrink-0 self-stretch object-contain md:w-36"
            />
            {/* <p className='text-xs'>Copyright © 2024 FWEN BOT - All Rights Reserved.</p> */}
            <p className='text-xs'>©</p>
        </div>
    )
}

export default Logo
