/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface LogoProps {
  src: string;
}

const Logo: React.FC<LogoProps> = ({ src }) => {
  return (
    <img
      loading="lazy"
      src={src}
      alt="Company Logo"
      className="object-contain shrink-0 self-stretch my-auto w-28 md:w-36 aspect-[4.12]"
    />
  );
};

export default Logo;
