/**
 * This code was generated by Builder.io.
 */
import Link from 'next/link'
import React from 'react'

interface NavigationItemProps {
    text: string
}

const NavigationItem: React.FC<NavigationItemProps> = ({ text }) => {
    return (
        <Link
            href={'/'}
            className="my-auto gap-2.5 self-stretch whitespace-nowrap rounded-xl bg-zinc-500 bg-opacity-0 px-4 py-2"
        >
            {text}
        </Link>
    )
}

export default NavigationItem
